[package]
name = "knuth-plass"
version = "0.1.0"
authors = ["sapir <yasapir@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
fixed = "1.1.0"
